# Generated by Django 3.2.7 on 2021-09-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postfile',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='postfile',
            old_name='post_id',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='posttags',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posttags',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
