# Generated by Django 3.2.7 on 2021-09-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210920_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTags',
            new_name='PostTag',
        ),
    ]
