# Generated by Django 3.2.7 on 2021-09-22 23:07

import api.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_posttags_posttag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfile',
            old_name='pos',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to=api.blogs.models.upload_image_to),
            preserve_default=False,
        ),
    ]
